#include "stdafx.h"

int DutTestEntry();
int TPM();
int Buzzer();
//int FAN();
int HWMonitor();
int SetRTC();
int CheckRTC();
int WriteMAC();
int Network();
int USB();
int CFCard();
int Memory();
//int LED();
//int ResetButton();
//int SwitchButton();
//int ByPass();
int CheckMAC();
int ShellMode();
//int PCIE();
//int HWVersion();
int SATA();
int VGA();
//int Console();
int CFDetail();
int HDDDetail();
int NetSpeed();
//int Reset();
int PowerButton();//自己添加的函数
int Wifi();//自己添加的函数
int Wifi5G();//自己添加的函数
int CPUStress();//自己添加的函数
int LTE_4G();
int ResetButton();
int SFP();
int HDMI();
int MicroUSB();
int GetComNum(const char* ProductID);
int WriteI211();
int PCIE();
int M2_ssd();
int FAN();
int CheckCPLD();
int LED();
int CheckDMI();